### ISSUE TITLE
Release version - snapshot

### ISSUE THREAD

**Issue by indusbull** [limansky/sbt-git-flow-version#4]
Hi there .... again!! 

We are grateful for this plugin to reduce some of the pain points we were having. As we are integrating this pluing with our Jenkins CI/CD pipeline, we are facing couple of issues. 

1. Is there any way output the version that is being built to console or file? Any command that can do this?
2. Is there option to not have snapshot versions in release branch? 

If you can point in right direction, I would be grateful.

Thank you!!

**Comment by limansky** [comment]
Hi,

  1. As for any sbt settingKey you can use `show version` to read the setting value.
  2. What version it should be? Just get it from matched part, but without adding snapshot suffix?

**Comment by limansky** [comment]
I think you can override versionPolicy with `prefix("release/") -> matching(false)`.

**Comment by indusbull** [comment]
1. `show version`  outputs the correct version. But I ended up creating custom task to handle Jenkins requirement.

2.  > I think you can override versionPolicy with `prefix("release/") -> matching(false)`.

This did the trick. 

Thank you for help and quick response.
